name: Java CI

on: [push, pull_request]

jobs:
  build:
    name: Build KG Parser
    runs-on: ubuntu-latest
    steps:
      - run: |
          mysql --version
          sudo mkdir -p /var/run/mysqld
          sudo chown mysql:mysql /var/run/mysqld
          sudo mysqld_safe --skip-grant-tables
          sudo mysql -u root -p -e "create database actions;"
