name: Java CI

on: [push, pull_request]

jobs:
  build:
    name: Build KG Parser
    runs-on: ubuntu-latest
    steps:
      - run: mysql --version
      - run: sudo systemctl start mysql
      - run: sudo mysql -uroot -proot -e "create database actions;"
      - run: pwd
